version: "2.3"

services:
  web:
    build:
      context: .
    volumes:
      - .:/usr/src/app
    ports:
      - '5000:5000'
    links:
      - db

  db:
    image: postgres:alpine
    environment:
      POSTGRES_USER: moby
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: ocean
