version: "2.3"

services:
  web:
    build:
      context: .
    volumes:
      - .:C:\app
    ports:
      - '8080:80'
    links:
      - db

  db:
    image: mcr.microsoft.com/mssql/server:2017-latest
    environment:
      ACCEPT_EULA: Y
      SA_PASSWORD: password
    ports:
      '1433:1433' -d
